[package]
name = "settle"
version = "0.4.7"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2" }
chrono = { version = "*" }
rusqlite = { version = "0.25.3", features = [ "backup" ] }
rayon = { version = "1.5.1" }
glob = { version = "0.3.0" }
regex = { version = "1.5.4" }
